-- DynamoDB table: split-sessions
--
-- This is documentation only — DynamoDB tables are created by deploy.sh.
-- The equivalent AWS CLI commands are:
--
--   aws dynamodb create-table \
--     --table-name split-sessions \
--     --attribute-definitions AttributeName=session_key,AttributeType=S \
--     --key-schema AttributeName=session_key,KeyType=HASH \
--     --billing-mode PAY_PER_REQUEST
--
--   aws dynamodb update-time-to-live \
--     --table-name split-sessions \
--     --time-to-live-specification "Enabled=true,AttributeName=ttl"
--
-- Table schema:
--   session_key  (String, PK) — "<channel_id>:<thread_ts>"
--   messages     (String)     — JSON array of {role, content} objects
--   ttl          (Number)     — Unix epoch; item auto-expires after 30 days
--
-- Free tier: DynamoDB on-demand billing has 200M requests/month free.
